### ISSUE TITLE
ENHANCEMENT: For a single repo with multiple projects, git hooks are awfully simple

### ISSUE THREAD

**Issue by marcosdly** [apamassociacao/APAM#16]
## Problema

Hooks atuais rodam independente do que está sendo comitado. Se eu tentar comitar algo em `backend/` ou na raiz do repositório, terei de esperar os testes e lint do frontend sucederem.

## Solução

Limitar commits a conter arquivos relativos a apenas um dos diretórios configurados. Arquivos na raiz do repositório ou outros diretórios não especificados podem ser comitados independentemente ou ser inclusos na mesma limitação: 1 **diretório especial** por commit.

## Motivo

Forçar testes a passarem sem erros em todos os commits vai resultar, eventualmente, em:
- Commits enormes;
- Delegar detalhes expressáveis em mensagens de commits para comentários ou lógica (abstrações, sintaxe, etc).

Ao envés de comitar `"feat: hidden popup navigation bar"`, por exemplo, eu, possivelmente, sentiria a necessidade de declarar
```typescript
class HiddenPopupNav {
  // ...
}
```
tal coisa que deveria ser (idealmente) ditada apenas pela necessidade do código ou diretrizes de escrita do mesmo, não por limitações de coisas cuja existência não afeta o funcionamento do programa (sistema de versionamento, por exemplo).

**Comment by marcosdly** [comment]
`.husky/pre-commit` atualizado: marcosdly/APAM@18db943a443c26a76a247f71b1237d71f2f85e6e

Esse patch resolve o bug em #15

**Comment by CarolineMartins09** [comment]
@Luiz-Suvilao @janlucasjm Por favor review ao colega pois esta esperando uma resposta! Obrigada

**Comment by marcosdly** [comment]
`pre-commit` pronto em marcosdly/APAM@6cdd0da15d11eb205281deed6dec0565d9f09900

**Comment by Luiz-Suvilao** [comment]
Pode criar o PR pro repo e mergear. 
Pra mim ta ok

**Comment by marcosdly** [comment]
Estava esperando alguma sugestão a respeito do `pre-push` @Luiz-Suvilao ... Vou fazer ele e criar um PR.

**Comment by marcosdly** [comment]
PR feito #18

Ainda não fiz o `pre-push` então decidi fazer o PR mesmo assim pra não deixar as contribuições paradas já que há prazo.

**Comment by marcosdly** [comment]
Fix (#18) merged f77a1bc754f0b61369c8c61041987e6d340e54db
